TECH_CATALOG = {
    # --- Lenguajes ---
    "python": "language",
    "javascript": "language",
    "typescript": "language",
    "java": "language",
    "kotlin": "language",
    "swift": "language",
    "go": "language",
    "rust": "language",
    "php": "language",
    "ruby": "language",
    "scala": "language",
    "perl": "language",
    "cobol": "language",
    "dart": "language",
    "elixir": "language",
    "groovy": "language",
    "c#": "language",
    "c++": "language",
    "objective-c": "language",
    "sql": "language",
    "bash": "language",
    "powershell": "language",

    # --- Frontend ---
    "react": "frontend",
    "angular": "frontend",
    "vue": "frontend",
    "svelte": "frontend",
    "next.js": "frontend",
    "nuxt": "frontend",
    "jquery": "frontend",
    "html": "frontend",
    "css": "frontend",
    "sass": "frontend",
    "tailwind": "frontend",
    "bootstrap": "frontend",
    "material ui": "frontend",
    "redux": "frontend",
    "zustand": "frontend",
    "storybook": "frontend",
    "webpack": "frontend",
    "vite": "frontend",
    "blazor": "frontend",

    # --- Mobile ---
    "react native": "mobile",
    "flutter": "mobile",
    "expo": "mobile",
    "android": "mobile",
    "ios": "mobile",
    "xamarin": "mobile",
    "ionic": "mobile",

    # --- Backend ---
    "node": "backend",
    "express": "backend",
    "nestjs": "backend",
    "django": "backend",
    "flask": "backend",
    "fastapi": "backend",
    "spring": "backend",
    "spring boot": "backend",
    "laravel": "backend",
    "symfony": "backend",
    "rails": "backend",
    "graphql": "backend",
    "grpc": "backend",
    "rest": "backend",
    ".net": "backend",
    "asp.net": "backend",
    "entity framework": "backend",
    "rabbitmq": "backend",

    # --- Bases de datos ---
    "postgresql": "database",
    "mysql": "database",
    "sql server": "database",
    "oracle": "database",
    "sqlite": "database",
    "mariadb": "database",
    "mongodb": "database",
    "redis": "database",
    "cassandra": "database",
    "dynamodb": "database",
    "elasticsearch": "database",
    "neo4j": "database",
    "db2": "database",
    "firebase": "database",
    "supabase": "database",

    # --- Datos ---
    "pandas": "data",
    "numpy": "data",
    "spark": "data",
    "pyspark": "data",
    "airflow": "data",
    "dbt": "data",
    "kafka": "data",
    "snowflake": "data",
    "databricks": "data",
    "bigquery": "data",
    "redshift": "data",
    "hadoop": "data",
    "hive": "data",
    "etl": "data",
    "power bi": "data",
    "tableau": "data",
    "looker": "data",
    "qlik": "data",
    "dax": "data",
    "power query": "data",
    "excel": "data",

    # --- ML / IA ---
    "tensorflow": "ml",
    "pytorch": "ml",
    "scikit-learn": "ml",
    "keras": "ml",
    "opencv": "ml",
    "langchain": "ml",
    "hugging face": "ml",
    "mlflow": "ml",
    "openai": "ml",
    "llm": "ml",
    "rag": "ml",
    "nlp": "ml",
    "machine learning": "ml",
    "deep learning": "ml",

    # --- Cloud ---
    "aws": "cloud",
    "azure": "cloud",
    "gcp": "cloud",
    "oci": "cloud",
    "lambda": "cloud",
    "s3": "cloud",
    "ec2": "cloud",
    "cloudformation": "cloud",
    "openshift": "cloud",

    # --- DevOps / Infra ---
    "docker": "devops",
    "kubernetes": "devops",
    "terraform": "devops",
    "ansible": "devops",
    "jenkins": "devops",
    "gitlab": "devops",
    "github actions": "devops",
    "circleci": "devops",
    "argocd": "devops",
    "sonarqube": "devops",
    "prometheus": "devops",
    "grafana": "devops",
    "datadog": "devops",
    "new relic": "devops",
    "nginx": "devops",
    "linux": "devops",
    "ci/cd": "devops",

    # --- Testing ---
    "junit": "testing",
    "mockito": "testing",
    "pytest": "testing",
    "jest": "testing",
    "cypress": "testing",
    "playwright": "testing",
    "selenium": "testing",
    "testing library": "testing",
    "postman": "testing",
    "soapui": "testing",
    "tdd": "testing",

    # --- Herramientas ---
    "git": "tooling",
    "github": "tooling",
    "bitbucket": "tooling",
    "jira": "tooling",
    "confluence": "tooling",
    "figma": "tooling",
    "sap": "tooling",

    # --- Mainframe ---
    "cics": "mainframe",
    "jcl": "mainframe",
    "vsam": "mainframe",
    "as400": "mainframe",
    "rpg": "mainframe",

    # --- Metodologías / arquitectura ---
    "scrum": "methodology",
    "kanban": "methodology",
    "agile": "methodology",
    "devops": "methodology",
    "microservicios": "architecture",
    "microservices": "architecture",
}